name: Format Code

on:
  push:
    branches:
      - develop

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Formatar código usando scripts do package.json
        run: |
          echo "Executando npm run format (Prettier e JS-Beautify)..."
          npm run format
          
      - name: Commitar alterações com o bot e coautor
        run: |
          # 1. Verificar se a formatação gerou alterações
          if [ -n "$(git status --porcelain)" ]; then

            AUTHOR_NAME="${{ github.actor }}"
            AUTHOR_EMAIL="$(git show -s --format='%ae' ${{ github.sha }})"
            
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            ALL_CHANGED_FILES=$(git diff --name-only || true)
            
            JS_CHANGED=$(echo "$ALL_CHANGED_FILES" | grep -E '\.(js|ts|jsx|tsx|css|scss)$' || true)
            
            HTML_CHANGED=$(echo "$ALL_CHANGED_FILES" | grep -E '\.html$' || true)

            COMMIT_MESSAGE_TITLE="style: Formatação automática de código"
            COMMIT_DETAILS=""

            if [ -n "$JS_CHANGED" ]; then
              COMMIT_DETAILS="$COMMIT_DETAILS — Prettier em JS/TS/CSS/SCSS"
            fi
            
            if [ -n "$HTML_CHANGED" ]; then
              COMMIT_DETAILS="$COMMIT_DETAILS — JS-Beautify em HTML"
            fi
            
            if [ -n "$COMMIT_DETAILS" ]; then
                COMMIT_MESSAGE_TITLE="$COMMIT_MESSAGE_TITLE$COMMIT_DETAILS"
            fi
            
            # Adiciona a linha Co-authored-by 
            COMMIT_MESSAGE="$COMMIT_MESSAGE_TITLE

            Co-authored-by: ${AUTHOR_NAME} <${AUTHOR_EMAIL}>"
            
            git add .
            git commit -m "$COMMIT_MESSAGE"
            
            echo "Committing style changes as bot, co-authored by ${AUTHOR_NAME}..."
            git push
          else
            echo "Nenhuma alteração de formatação detectada. Nada para commitar."
          fi
